[#215] 예약 단계 삭제 api
softeerbootcamp-3rd/Team10-GENE10S pull request #219
Opened 2024-02-19 10:10 UTC by Tin9oo

## ✨ 작업 내용
1. unique 제약조건 추가
2. 예약 진행 단계 삭제 api
3. 최상위 단계를 현재 단계로 저장하는 모듈 개발

## 📎 상세 설명 (스크린샷 포함 가능)
1. unique 제약조건을 추가
> 하나의 예약 id에 대해 동일한 예약 단계가 있으면 안된다고 판단하여 step 테이블의 reservation_id, stage에 unique 제약조건을 추가했습니다.

2. 예약 진행 단계 삭제 api
> 요청의 진행 단계에 해당하는 레코드를 삭제합니다.

```java
@Transactional
public void deleteStage(AdminRequest.StageInfo requestBody) {
    Long stepId = stepRepository.findStepByReservationIdAndStage(
            requestBody.getReservationId(),
            requestBody.getProgress().getName()).getId();

    stepRepository.deleteById(stepId);

    setLatestStage(requestBody);
}
```

3. 최상위 단계를 현재 단계로 저장하는 모듈 개발
> 진행 단계를 추가/삭제한 후 모듈을 실행하여, 진행 단계 중 최상위 단계를 현재 예약의 진행 단계로 지정합니다.

```java
private void setLatestStage(AdminRequest.StageInfo requestBody) {
    // 예약 현황 갱신
    Reservation reservation = reservationRepository.findReservationById(requestBody.getReservationId());

    List<ProgressStage> stages = stepRepository.findStagesByReservationId(requestBody.getReservationId()).stream()
            .map(ProgressStage::fromName)
            .collect(Collectors.toList());

    reservation.setProgressStage(stages.stream()
            .max(Enum::compareTo)
            .orElse(null)
            .getName()
    );

    reservationRepository.save(reservation);
}
```

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들
- `@Transactional`
> `@Transactional` 어노테이션은 스프링 프레임워크에서 제공하는 어노테이션으로, 트랜잭션을 지원하는 메서드에 사용됩니다. 이 어노테이션을 메서드나 클래스에 지정하면 해당 메서드나 클래스의 모든 public 메서드에 대해 트랜잭션 관리가 자동으로 적용됩니다.
>
> `@Transactional`이 없으면 메서드 실행마다 DB 작업이 각각 별개의 트랜잭션으로 처리됩니다. 각각의 DB 작업이 독립적으로 처리되면 데이터 일관성 문제가 발생할 수 있습니다. 따라서, 트랜잭션 관리가 필요한 메서드에는 `@Transactional` 어노테이션을 명시적으로 추가하는 것이 좋습니다. 이렇게 하면 해당 메서드에서 실행되는 모든 데이터베이스 작업이 하나의 트랜잭션으로 묶입니다.

2024-02-19 16:02 UTC, PKafka0320 commented on server/src/main/java/com/genesisairport/reservation/service/admin/AdminReservationService.java
> +        reservationRepository.save(reservation);
stepRepository.save() 처럼 repository에 저장하는 메서드라고 생각했는데, 이부분에는 try catch를 사용하지 않은 이유가 있으신가요?

2024-02-19 16:26 UTC, Tin9oo commented on server/src/main/java/com/genesisairport/reservation/service/admin/AdminReservationService.java
> +        reservationRepository.save(reservation);
`stepRepository.save()`는 Unique 제약조건으로 인해 중복 값 입력 시 예외처리됩니다.

그에 반해 `reservationRepository.save(reservation)`은 reservation 테이블의 progress_stage를 update하는 코드입니다. 이때, step 테이블의 현재 reservation_id에 해당하는 진행 단계 중 최상위의 단계로 update만 수행하기 때문에 try-catch 구문을 사용하지 않았습니다.

혹시 제가 찾지 못한 예외 상황이 있다면 알려주시면 감사하겠습니다 ☺️

2024-02-20 00:55 UTC, PKafka0320 approved these changes

2024-02-20 01:20 UTC, taegon98 requested changes

2024-02-20 01:20 UTC, taegon98 commented on server/src/main/java/com/genesisairport/reservation/common/ProgressStage.java
> +        throw new IllegalArgumentException("Invalid stage name: " + name);
이 부분은 GeneralException으로 처리하면 어떨까요?

2024-02-20 01:20 UTC, taegon98 commented on server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
> +@Setter
Setter를 사용하실거라면, 메서드로 특정 필드에 대한 set 함수를 만드는 방식은 어떨까요?

2024-02-20 01:36 UTC, Tin9oo commented on server/src/main/java/com/genesisairport/reservation/common/ProgressStage.java
> +        throw new IllegalArgumentException("Invalid stage name: " + name);
말씀하신 GeeneralException으로 처리하는게 더 좋겠네요^^

해당 부분 수정했습니다~

2024-02-20 01:38 UTC, Tin9oo commented on server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
> +@Setter
이후 정비소 코멘트 api를 개발 할 때 공통적으로 set 함수가 필요할 것이라 판단했습니다.

set 함수가 많아질 것 같은데 그래도 Setter를 사용하지 않는게 좋을까요?

2024-02-20 01:40 UTC, taegon98 commented on server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
> +@Setter
> 이후 정비소 코멘트 api를 개발 할 때 공통적으로 set 함수가 필요할 것이라 판단했습니다.
> 
> set 함수가 많아질 것 같은데 그래도 Setter를 사용하지 않는게 좋을까요?
특정 필드에 대해서만 Set을 한다면, 해당 필드들을 모아놓은 공통 메서드로 분리하게 되면 무분별한 set을 막을 수 있을거같아서 좋다고 생각했습니다!

2024-02-20 01:45 UTC, Tin9oo commented on server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
> +@Setter
말씀하신 의도 이해했습니다. 필드 단위로 setter를 사용하는 방식이 무분별한 set을 막을 수 있겠네요. 수정하겠습니다.

2024-02-20 01:54 UTC, Tin9oo commented on server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
> +@Setter
Reservation 엔티티를 제외한 다른 엔티티에도 필요한 필드에 Setter를 지정하도록 수정했습니다~

2024-02-20 02:01 UTC, taegon98 approved these changes

2024-02-20 02:01 UTC, merged