[#239] 관리자 예약 관리 페이지 API 연결
softeerbootcamp-3rd/Team10-GENE10S pull request #246
Opened 2024-02-21 09:21 UTC by h-sooah

## ✨ 작업 내용

1. 예약 검색 API 연결

2. 예약 내역 검색 API Request 형식 변경

## 📎 상세 설명 (스크린샷 포함 가능)

### 예약 검색 API 연결

- `/api/Reservation.js` 에서 예약 내역 검색 API 함수 구현

- '검색' 버튼 누르면 검색 조건에 맞는 데이터 표시

- 'NO', '센터 방문', '픽업' 누를 때마다 오름차순/내림차순 정렬

### 예약 검색 내역 API Request 형식 변경

#### ResponseBody 사용하는 방식에서 RequestParam 사용하는 방식으로 변경

[ 기존 ]

```java
    @GetMapping("/all")
    public ResponseEntity<ResponseDto> searchAllReservations(
            HttpServletRequest request,
            @RequestBody AdminRequest.ReservationDetail requestBody)
```

[ 수정 ]

```java
    @GetMapping("/all")
    public ResponseEntity<ResponseDto> searchAllReservations(
            HttpServletRequest request,
            @RequestParam(value = "shopName", required = false) String shopName,
            @RequestParam(value = "startPickUpDateTime", required = false) String startPickUpDateTime,
            @RequestParam(value = "endPickUpDateTime", required = false) String endPickUpDateTime,
            @RequestParam(value = "startReturnDateTime", required = false) String startReturnDateTime,
            @RequestParam(value = "endReturnDateTime", required = false) String endReturnDateTime,
            @RequestParam(value = "customerName", required = false) String customerName,
            @RequestParam(value = "sellName", required = false) String sellName,
            @RequestParam(value = "stage", required = false) String stage,
            @RequestParam(value = "sortColumn", required = false) String sortColumn,
            @RequestParam(value = "sortDirection", required = false) String sortDirection,
            @RequestParam(value = "pageSize", required = false) String pageSize,
            @RequestParam(value = "pageNumber", required = false) String pageNumber)
```

## 📎 필요한 후속 작업

- 페이지네이션 적용

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

x

2024-02-21 10:49 UTC, h-sooah commented on admin/src/components/CustomCalendar.js
> +  display: ${(props) => (props.$isOpen ? "block" : "none")};
이 부분은 추후 Wiki로 작성하겠습니다!

2024-02-21 10:49 UTC, h-sooah commented on admin/src/components/CustomCalendar.js
> +  position: relative;
주의하겠습니다~

2024-02-22 01:45 UTC, insiderhj requested changes

2024-02-22 01:45 UTC, insiderhj commented on admin/src/pages/ReservationList.js
> +                            <div>현재 단계 </div>
제가 까먹고 Figma에 속성을 안 적었는데... 각 td마다 width가 지정돼 있어요.

아마 100, 150, 200, 250, 300, 350 중에 하나일 거예요
요렇게 변경해주시면 좋을 것 같아요

style.scss:
```
.w-100 {
    width: 100px !important;
}

.w-150 {
    width: 150px !important;
}

...
```

ReservationList.js:
```
<div className={classNames('td', 'w-100')}>
    ...
</div>
```

2024-02-22 01:45 UTC, insiderhj commented on admin/src/pages/ReservationList.js
> +                    ))}
여기도 마찬가지로 width 속성 추가해주세용

2024-02-22 01:45 UTC, insiderhj commented on server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
> +    ) {
이건 요청까지는 아니고 제안인데, Controller에서 Service로 넘어갈 때에는 class 하나 만들어서 오브젝트로 넘기면 어떨까요? 파라미터가 넘 많아서요

2024-02-22 01:52 UTC, h-sooah commented on admin/src/pages/ReservationList.js
> +                            <div>현재 단계 </div>
수정하겠습니다.

2024-02-22 01:52 UTC, h-sooah commented on admin/src/pages/ReservationList.js
> +                    ))}
얘도 수정하겠습니다.

2024-02-22 01:52 UTC, h-sooah commented on server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
> +    ) {
좋은 의견이네요~ 반영하겠습니다.

2024-02-22 02:24 UTC, insiderhj approved these changes

2024-02-22 02:24 UTC, insiderhj commented on admin/src/components/CustomCalendar.js
> +          <CalendarWrapper $isOpen={isOpen}>
이런 기능도 있군요~ 좋은 것 같아요

2024-02-22 02:25 UTC, insiderhj commented
고생하셨습니다~

2024-02-22 02:25 UTC, PKafka0320 approved these changes

2024-02-22 02:34 UTC, merged